set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_mode[0]}]

set_property PACKAGE_PIN F6 [get_ports {current_mode[7]}]
set_property PACKAGE_PIN G4 [get_ports {current_mode[6]}]
set_property PACKAGE_PIN G3 [get_ports {current_mode[5]}]
set_property PACKAGE_PIN J4 [get_ports {current_mode[4]}]
set_property PACKAGE_PIN H4 [get_ports {current_mode[3]}]
set_property PACKAGE_PIN J3 [get_ports {current_mode[2]}]
set_property PACKAGE_PIN J2 [get_ports {current_mode[1]}]
set_property PACKAGE_PIN K2 [get_ports {current_mode[0]}]
